site_name: MoonCord Wiki
site_url: https://wiki.tludwig.dev/mooncord
repo_url: https://github.com/eliteSchwein/mooncord
edit_uri: edit/dev/docs/content/docs/
nav:
  - Home: index.md
  - Installation: install.md
  - Usage:
      - Discord:
          - /admin: sites/Usage/Discord/admin.md
          - /config: sites/Usage/Discord/config.md
          - /dump: sites/Usage/Discord/dump.md
          - /editchannel: sites/Usage/Discord/editchannel.md
          - /emergencystop: sites/Usage/Discord/emergencystop.md
          - /execute: sites/Usage/Discord/execute.md
          - /fileinfo: sites/Usage/Discord/fileinfo.md
          - /getuserid: sites/Usage/Discord/getuserid.md
          - /history: sites/Usage/Discord/history.md
          - /info: sites/Usage/Discord/info.md
          - /listgcodes: sites/Usage/Discord/listgcodes.md
          - /listlogs: sites/Usage/Discord/listlogs.md
          - /listtimelapses: sites/Usage/Discord/listtimelapses.md
          - /notifyme: sites/Usage/Discord/notifyme.md
          - /pidtune: sites/Usage/Discord/pidtune.md
          - /power: sites/Usage/Discord/power.md
          - /preheat: sites/Usage/Discord/preheat.md
          - /printjob: sites/Usage/Discord/printjob.md
          - /reset: sites/Usage/Discord/reset.md
          - /restart: sites/Usage/Discord/restart.md
          - /status: sites/Usage/Discord/status.md
          - /systeminfo: sites/Usage/Discord/systeminfo.md
          - /temp: sites/Usage/Discord/temp.md
          - /tune: sites/Usage/Discord/tune.md
      - GCode:
          - invite: sites/Usage/GCode/invite.md
          - broadcast: sites/Usage/GCode/broadcast.md
          - prompt: sites/Usage/GCode/prompt.md
      - OS:
          - systemctl: sites/Usage/OS/systemctl.md
          - docker: sites/Usage/OS/docker.md
  - Configuration:
      - "[connection]": sites/Configuration/connection.md
      - "[logger]": sites/Configuration/logger.md
      - "[webcam NAME]": sites/Configuration/webcam.md
      - advanced:
          - "[status]": sites/Configuration/Advanced/status.md
          - "[snapshot]": sites/Configuration/Advanced/snapshot.md
          - "[message]": sites/Configuration/Advanced/message.md
          - "[general]": sites/Configuration/Advanced/general.md
          - "[language]": sites/Configuration/Advanced/language.md
          - placeholder: sites/Configuration/Advanced/placeholder.md
          - embed:
              - "[color NAME]": sites/Configuration/Advanced/Embed/color.md
              - "[icon NAME]": sites/Configuration/Advanced/Embed/icon.md
              - "[status NAME]": sites/Configuration/Advanced/Embed/status.md
              - "[embed NAME]": sites/Configuration/Advanced/Embed/embed.md
  - Misc:
      - "Setup Mode": sites/Misc/setupmode.md
      - "Multi Installation": sites/Misc/multiinstall.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
theme:
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
  name: readthedocs
  features:
    - content.action.edit
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - content.code.copy
  font: false
  logo: img/logo.png
  favicon: img/logo.png
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/triangle-exclamation
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left