module.exports = {
  addaccess: require('./addaccess'),
  addadmin: require('./addadmin'),
  addchannel: require('./addchannel'),
  execute: require('./execute'),
  generalaccess: require('./generalaccess'),
  help: require('./help'),
  info: require('./info'),
  hsinfo: require('./hsinfo'),
  listprints: require('./listprints'),
  pause: require('./pause'),
  print: require('./print'),
  reboot: require('./reboot'),
  removeaccess: require('./removeaccess'),
  removeadmin: require('./removeadmin'),
  removechannel: require('./removechannel'),
  resume: require('./resume'),
  shutdown: require('./shutdown'),
  status: require('./status'),
  stop: require('./stop'),
  temp: require('./temp')
}
